import { createElement } from 'lwc';
import ParentComponent from 'c/parentComponent';

describe('c-parent-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-parent-component', {
            is: ParentComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
         const lightninginput = element.shadowRoot.querySelector('lightning-input');
         lightninginput.value = 'hey';
        expect(lightninginput.value).toBe('hey');
    });
});